name: Build for release

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install cmake conan && make install

    - name: Build release package
      run: make prod

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-sf3convert
        path: build/Prod/sf3convert
        retention-days: 28

    - name: Test conversion
      run: make test-prod
  build-windows:
    runs-on: window-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install cmake conan && make install

    - name: Build release package
      run: make window

    - uses: actions/upload-artifact@v4
      with:
        name: window-sf3convert
        path: build/Prod/sf3convert
        retention-days: 28

    - name: Test conversion
      run: make test-prod
