name: Build for release

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - name: Cache Conan Dependencies
      id: build-ubuntu-cache-conan
      uses: actions/cache@v2
      with:
        path: /home/runner/.conan2
        key: build-ubuntu-cache-conan

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install cmake conan && make install

    - name: Build release package
      run: make prod

    - uses: actions/upload-artifact@v4
      with:
        name: ubuntu-sf3convert
        path: build/Prod/sf3convert
        retention-days: 28

    - name: Test conversion
      run: make test-prod

  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - name: Cache Conan Dependencies
      id: build-macos-cache-conan
      uses: actions/cache@v2
      with:
        path: /Users/runner/.conan2
        key: build-macos-cache-conan

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install cmake conan && make install

    - name: Build release package
      run: make prod

    - uses: actions/upload-artifact@v4
      with:
        name: macos-sf3convert
        path: build/Prod/sf3convert
        retention-days: 28

    - name: Test conversion
      run: make test-prod

  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - name: Cache Conan Dependencies
      id: build-windows-cache-conan
      uses: actions/cache@v2
      with:
        path: C:\Users\runneradmin\.conan2
        key: build-windows-cache-conan

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: choco install cmake conan && make install

    - name: Build release package
      run: make window

    - uses: actions/upload-artifact@v4
      with:
        name: window-sf3convert
        path: build/Prod/sf3convert
        retention-days: 28

    - name: Test conversion
      run: make test-prod
