name: Build for release

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install cmake ninja conan && make install

    - name: Build release package
      run: make dev

    - uses: actions/upload-artifact@v4
      with:
        name: ubuntu-sf3convert
        path: build/Dev/sf3convert
        retention-days: 28

    - name: Test conversion
      run: make test-dev

  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install cmake ninja conan && make install

    - name: Build release package
      run: make dev

    - uses: actions/upload-artifact@v4
      with:
        name: macos-sf3convert
        path: build/dev/sf3convert
        retention-days: 28

    - name: Test conversion
      run: make test-dev

  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install cmake conan && make install

    - name: Build release package
      run: make window

    - uses: actions/upload-artifact@v4
      with:
        name: window-sf3convert
        path: build/Prod/sf3convert
        retention-days: 28

    - name: Test conversion
      run: make test-prod
